add support for pgsql filter & modules
grafeas/grafeas-pgsql pull request #11
Opened 2021-11-18 08:15 UTC by hkadakia

This PR adds support for using filters in PgSQL. It also moves some of the code from grafeas to this repo & fixes some bugs in the process.

2021-11-18 08:16 UTC, hkadakia commented
@aysylu @wkozlik Please help review.

2021-11-20 00:07 UTC, aysylu requested changes
This is very cool! Couple minor pieces of feedback.

2021-11-20 00:07 UTC, aysylu commented on go/v1beta1/storage/filter.go
> +	/*
Is this meant as testing code?

2021-11-20 00:07 UTC, aysylu commented on go/v1beta1/storage/filter.go
> +	// log.Println(result.Expr.GetCallExpr().Args[1].GetCallExpr().Args[0].GetIdentExpr().Name)
could you please remove the debugging statements that are no longer needed?

2021-11-23 17:13 UTC, aysylu approved these changes

2021-11-23 17:13 UTC, aysylu commented
Thanks for this great contribution, @hkadakia!

2021-11-23 17:13 UTC, merged